# Generated by Django 3.2.12 on 2024-02-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0002_auto_20240215_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, upload_to='static/users_avatars'),
        ),
    ]
