# Generated by Django 4.1.3 on 2024-02-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0004_project_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
