# Generated by Django 4.1.3 on 2024-02-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0005_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
