# Generated by Django 4.1.3 on 2024-02-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0006_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
