# Generated by Django 3.2.12 on 2024-02-20 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0008_alter_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='workers',
            field=models.ManyToManyField(related_name='task_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
