# Generated by Django 3.2.12 on 2024-02-20 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0009_alter_tasks_workers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='static/users_avatars'),
        ),
    ]
