# Generated by Django 3.2.12 on 2024-03-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0013_auto_20240309_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_sentMail',
            field=models.BooleanField(default=False),
        ),
    ]
