# Generated by Django 6.0 on 2025-12-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0016_paypalpayment_enabletax_paypalpayment_itemslist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foo',
        ),
        migrations.DeleteModel(
            name='LastMail',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='workers',
        ),
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
