# Generated by Django 6.0 on 2025-12-31 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0018_typeofconfig_alter_user_options_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofconfig',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='static/type_of_config_images'),
        ),
        migrations.AlterField(
            model_name='typeofconfig',
            name='type',
            field=models.CharField(choices=[('breed', 'Breed'), ('pet_type', 'Pet Type'), ('animal_types', 'Animal Types'), ('animal_gender', 'Animal Gender'), ('neutering_status', 'Neutering Status')], default='breed', max_length=200),
        ),
    ]
