# Generated by Django 3.2.12 on 2024-03-26 16:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0018_auto_20240324_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(blank=True, null=True, related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
