# Generated by Django 3.2.12 on 2024-04-02 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0020_auto_20240402_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='managers',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='workers',
            field=models.ManyToManyField(related_name='task_workers', to=settings.AUTH_USER_MODEL),
        ),
    ]
