# Generated by Django 6.0 on 2026-01-18 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0021_pet_date_of_birth_pet_gender_pet_health_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofconfig',
            name='parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_types', to='example.typeofconfig'),
        ),
    ]
