# Generated by Django 3.2.12 on 2024-05-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0022_auto_20240402_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='costCode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='quantity',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
