# Generated by Django 3.2.12 on 2024-05-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0023_auto_20240511_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='fileID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='color',
            field=models.CharField(default='#71adfc', max_length=200),
        ),
    ]
