# Generated by Django 3.2.12 on 2024-05-16 18:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0024_auto_20240516_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='fileID',
            new_name='fileName',
        ),
        migrations.AddField(
            model_name='project',
            name='uploaded_files',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=[], size=None),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='color',
            field=models.CharField(default='#4649af', max_length=200),
        ),
    ]
